// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbavwtwslofcrpeuyqak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiYXZ3dHdzbG9mY3JwZXV5cWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDQxNzksImV4cCI6MjA2OTc4MDE3OX0.eSd88VEGv78YoNjuBxR5PpwnpN6BZ4Am4z3Cq8xHUds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});